### PR TITLE
delete unused  config calls

### PR DESCRIPTION
**Pull request by yelizariev**
Author is overridden later in "git commit" command

### CODE REVIEW

**Comment by stefanzweifel** [comment]
Hi Ivan,

Thanks for your PR. I would like to keep these config calls, as the resulting commit will have both the real user and GitHub Actions as the author.

Screen-Shot-2019-12-10-13-39-48 85

Or is this causing problems somewhere in your workflow?

**Comment by yelizariev** [comment]
That double authoring comes other settings and will not be changed after merging this PR.

 From my understanding, one author is from the authentication, i.e.
``` 
        login $GITHUB_ACTOR
        password $GITHUB_TOKEN
```

While another author is from ``--author`` attribute, which is overriding of ``user.email`` and ``user.name``. I didn't check it, though I'm quite sure about it. See also https://www.git-tower.com/learn/git/faq/change-author-name-email

Assuming, that I'm right, I'd like this PR be merged, because I plan to send another PR with new feature about custom author

**Comment by stefanzweifel** [comment]
As far as I remember, the code which is stored into the `.netrc` file is only responsible for authenticating with GitHub (required for `git push`)

`git config --global user.email` sets the default user/author for the commits.

---

I'm reopening the PR. Have to test this 🙃

**Comment by stefanzweifel** [comment]
I've just tested these changes in a test project and the Action fails, as git can't determine a user.
Please feel free to open an issue or PR for your idea to customize the author.

```
*** Please tell me who you are.

Run
  git config --global user.email "you@example.com"

  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@6df3b3a11f8a.(none)')
```

Screen-Shot-2019-12-10-20-22-12 05

**Pull request closed without merging**
