### PR TITLE
Install Git-LFS while building Dockerfile

### PR DESCRIPTION
**Pull request by jkaan**
Hi there!

As we discussed, the PR to install git-lfs while building the Dockerfile :). Let me know if you would like me to change commit messages or something

### CODE REVIEW

**Comment by stefanzweifel** [comment]
Thanks 👍 

Have you tested the changes in a repository? We don't have a test suite (yet).

**Comment by jkaan** [comment]
@stefanzweifel I have not actually, how can I easily do that?

**Comment by stefanzweifel** [comment]
You can use your fork by adding the following code to a workflow of yours:

```yaml
- uses: jkaan/git-auto-commit-action@feature/add-support-for-lfs
  with:
    commit_message: Apply automatic changes
    branch: ${{ github.head_ref }}
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I will test it too, just wanted to ask if you did any tests yet :)

**Comment by jkaan** [comment]
I've just tried it on a project of mine which has LFS enabled and it worked :).

**Comment by stefanzweifel** [comment]
I also tested it in a repo without LFS. Works great. Will merge to master and tag a new version soon.

**Pull request merged**
