### PR TITLE
WIP: Update to actions/checkout@v2

### PR DESCRIPTION
**Pull request by staabm**
See https://github.com/actions/checkout/releases/tag/v2.0.0

### CODE REVIEW

**Comment by staabm** [comment]
hmm I just tried this in a private repo.. it seems the php-cs-fixer example does not work with `actions/checkout@v2`..  is there any known issue?

**Comment by stefanzweifel** [comment]
@staabm I haven't used checkout@v2 yet, but another user messaged me just yesterday, that something didn't work: https://github.com/TomasVotruba/tomasvotruba.com/pull/905#event-2928907067. Unfortunately the logs are gone, but the error looked something like "pathspec $branch not available".

**Comment by staabm** [comment]
yeah, thats the same error I see in my private builds.

**Comment by stefanzweifel** [comment]
Thanks for pointing this out btw! 
I know it's frustrating that the action doesn't work. I'm probably more frustrated as I want the action to work in every scenario and in conjunction with other actions.

I will have a closer look over the next few days.

**Comment by stefanzweifel** [comment]
@staabm I could figure out a solution to use checkout@v2. [Here](https://github.com/stefanzweifel/git-auto-commit-action-demo-app/pull/7/files#diff-5a5ecd9754f31f844b225a164c6e2784R14-R16) are the changes I made in my demo/test application. (Only tested with the `on: pull_request`-event)

I will merge your PR and update the README accordingly so other know how to use the action with checkout@v2.

**Pull request closed without merging**
