### PR TITLE
Creating orphan branch

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
This provides the ability to create an orphan branch if $INPUT_BRANCH doesn't exist.

**Comment by stefanzweifel** [comment]
Hi 👋

Never heard of orphan branches before. So I'm curious: in which scenarios are such branches useful?
If this should be merged, I would have to be able to answer possible questions.

Maybe you can give an example workflow file?

**Comment by StrongMonkey** [comment]
@stefanzweifel Hi :wave: , thanks for replying!

This is actually a specific usecase that we want to commit on another branch, and if the branch doesn't exist, created an orphan branch(which has no git history). 

We use this on one of our repo so that we can commit generated changes to another branch without creating empty branch manually. Here is an example https://github.com/StrongMonkey/charts-1/blob/branch-asset/.github/workflows/push.yml#L18-L22

**Comment by stefanzweifel** [comment]
Sounds reasonable.
I also searched a bit around and I think that's actually a pretty cool feature. Would have been helpful to now it exists in the past 😅

Will merge and tag a new version soon.

**Comment by pi0** [comment]
Hi guys! For some reason `INPUT_BRANCH` is empty: https://github.com/nuxt/create-nuxt-app/runs/1098566291?check_suite_focus=true#step:7:21

I even tried using an env but no luck https://github.com/nuxt/create-nuxt-app/blob/master/.github/workflows/snapshot.yml#L40

**Comment by stefanzweifel** [comment]
@pi0 Thanks for reporting! Seems this PR really has broken everything. Sorry for that.

The changes have been reverted in #97 and released in `v4.5.1`.

@StrongMonkey For your own workflows, you would have to revert to your fork for now. Will work on a test suite over the next few days/weeks to make sure new features can be added with confidence.

**Pull request merged**
